#!/bin/bash

PGDUMP=/usr/pgsql-12/bin/psql
PORT=5432
BACKUP_LOCATION=/data/backup/mosip/script
LOGFILE=$BACKUP_LOCATION/credential_transaction.log
DB_NAME=test
BACKUP_USER=postgres
BACKUP_PASS='xxxx'

PROC1="select * from test;"
# Perform update query credential_transaction
echo "$(date) : [$PROC1] IS STARTED" >> $LOGFILE;
# FOR PROC1
PGPASSWORD=$BACKUP_PASS $PGDUMP --host localhost --port $PORT  -U $BACKUP_USER -d $DB_NAME -c "$PROC1" 2>> $LOGFILE
echo "$(date) : [$PROC1] IS  FINISHED" >> $LOGFILE;

exit
